/**
 *
 * $Id$
 */
package e3value.validation;

import e3value.DependencyElement;
import e3value.StimulusElement;
import e3value.ValueActivity;
import e3value.ValueInterface;
import e3value.ValueObject;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link e3value.BusinessActor}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface BusinessActorValidator {
	boolean validate();

	boolean validateName(String value);
	boolean validateHasValueInterfaces(EList<ValueInterface> value);
	boolean validateHasValueActivities(EList<ValueActivity> value);
	boolean validateHasStimulusElements(EList<StimulusElement> value);
	boolean validateHasDependenceElements(EList<DependencyElement> value);
	boolean validateHasValueObjects(EList<ValueObject> value);
}
