/**
 *
 * $Id$
 */
package e3value.validation;

import e3value.DependencyElement;

/**
 * A sample validator interface for {@link e3value.ConnectionElement}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ConnectionElementValidator {
	boolean validate();

	boolean validateSourceDependenceElement(DependencyElement value);
	boolean validateTargetDependenceElement(DependencyElement value);
}
