/**
 *
 * $Id$
 */
package e3value.validation;

import e3value.BusinessActor;
import e3value.ValueActivity;

/**
 * A sample validator interface for {@link e3value.DependencyElement}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface DependencyElementValidator {
	boolean validate();

	boolean validateInBusinessActor(BusinessActor value);
	boolean validateInValueActivity(ValueActivity value);
}
