/**
 *
 * $Id$
 */
package e3value.validation;

import e3value.BusinessActor;
import e3value.DependencyElement;
import e3value.E3ValueDiagram;
import e3value.ValueExchange;
import e3value.ValueObject;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link e3value.E3ValueModel}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface E3ValueModelValidator {
	boolean validate();

	boolean validateHasValueExchanges(EList<ValueExchange> value);
	boolean validateInE3ValueDiagram(E3ValueDiagram value);
	boolean validateHasBusinessActors(EList<BusinessActor> value);
	boolean validateHasValueObjects(EList<ValueObject> value);
	boolean validateHasDependenceElements(EList<DependencyElement> value);
}
