/**
 *
 * $Id$
 */
package e3value.validation;

import e3value.InputPort;
import e3value.OutputPort;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link e3value.JoinElement}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface JoinElementValidator {
	boolean validate();

	boolean validateHasInputPorts(EList<InputPort> value);
	boolean validateHasOutputPort(OutputPort value);
}
