/**
 *
 * $Id$
 */
package e3value.validation;

import e3value.ForkElement;
import e3value.JoinElement;

/**
 * A sample validator interface for {@link e3value.OutputPort}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface OutputPortValidator {
	boolean validate();

	boolean validateInForkElement(ForkElement value);
	boolean validateInJoinElement(JoinElement value);
}
