/**
 *
 * $Id$
 */
package e3value.validation;

import e3value.E3ValueModel;
import e3value.ValueObject;
import e3value.ValuePort;

/**
 * A sample validator interface for {@link e3value.ValueExchange}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ValueExchangeValidator {
	boolean validate();

	boolean validateSourceValuePort(ValuePort value);
	boolean validateTargetValuePort(ValuePort value);
	boolean validateHasValueObject(ValueObject value);
	boolean validateInE3ValueModel(E3ValueModel value);
}
