/**
 *
 * $Id$
 */
package e3value.validation;

import e3value.ValueExchange;
import e3value.ValueInterface;

/**
 * A sample validator interface for {@link e3value.ValuePortIn}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ValuePortInValidator {
	boolean validate();

	boolean validateInConnectWithValueExchange(ValueExchange value);
	boolean validateInValueInterface(ValueInterface value);
}
