/**
 *
 * $Id$
 */
package e3value.validation;

import e3value.BusinessActor;
import e3value.ResponsabilityElement;
import e3value.ValueActivity;
import e3value.ValuePortIn;
import e3value.ValuePortOut;

/**
 * A sample validator interface for {@link e3value.ValueInterface}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ValueInterfaceValidator {
	boolean validate();

	boolean validateInBusinessActor(BusinessActor value);
	boolean validateInValueActivity(ValueActivity value);
	boolean validateHasValuePortIn(ValuePortIn value);
	boolean validateHasValuePortOut(ValuePortOut value);
	boolean validateBindsResponsabilityElement(ResponsabilityElement value);
}
